modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="salju_ladders"
version="2.4.0"
displayName="Better Ladders"
credits="Jusey1"
displayURL="https://discord.gg/s7QaYGUzZU"
authors="Jusey1"
description="Improves ladder placement."

[[dependencies.salju_ladders]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




